services:

  postgres:
    image: postgres:16
    container_name: homelab-postgres
    restart: always

    environment:
      POSTGRES_USER: homelab
      POSTGRES_PASSWORD: homelab123
      POSTGRES_DB: homelabdb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  api:
    build: ./api/homelab.api
    container_name: homelab-api

    ports:
      - "5000:8080"

    depends_on:
      - postgres


volumes:
  postgres_data: