// <auto-generated />
using System;
using Homelab.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Homelab.Data.Migrations
{
    [DbContext(typeof(HomelabContext))]
    [Migration("20260315162514_NovaMigration")]
    partial class NovaMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "CriticalityLevel", new[] { "LOW", "MEDIUM", "HIGH", "CRITICAL" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "MovementType", new[] { "IN", "OUT", "ADJUSTMENT", "TRANSFER" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "OAuthProvider", new[] { "GOOGLE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "PasswordStatus", new[] { "ACTIVE", "INACTIVE" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Homelab.Data.Data.Entities._prisma_migration", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<int>("applied_steps_count")
                        .HasColumnType("integer");

                    b.Property<string>("checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("finished_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("logs")
                        .HasColumnType("text");

                    b.Property<string>("migration_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("rolled_back_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("started_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("id")
                        .HasName("_prisma_migrations_pkey");

                    b.ToTable("_prisma_migrations");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.audit_events_202603", b =>
                {
                    b.Property<DateTime>("occurred_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValueSql("(gen_random_uuid())::text");

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("criticality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("duration_ms")
                        .HasColumnType("integer");

                    b.Property<string>("endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("permission_alias")
                        .HasColumnType("text");

                    b.Property<string>("permission_id")
                        .HasColumnType("text");

                    b.Property<int?>("status_code")
                        .HasColumnType("integer");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("user_email")
                        .HasColumnType("text");

                    b.Property<string>("user_id")
                        .HasColumnType("text");

                    b.HasKey("occurred_at", "id")
                        .HasName("audit_events_202603_pkey");

                    b.HasIndex(new[] { "occurred_at" }, "audit_events_202603_occurred_at_idx");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "occurred_at" }, "audit_events_202603_occurred_at_idx"), "brin");

                    b.HasIndex(new[] { "user_id", "occurred_at" }, "audit_events_202603_user_id_occurred_at_idx")
                        .IsDescending(false, true);

                    b.ToTable("audit_events_202603", (string)null);
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.audit_events_202604", b =>
                {
                    b.Property<DateTime>("occurred_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValueSql("(gen_random_uuid())::text");

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("criticality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("duration_ms")
                        .HasColumnType("integer");

                    b.Property<string>("endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("permission_alias")
                        .HasColumnType("text");

                    b.Property<string>("permission_id")
                        .HasColumnType("text");

                    b.Property<int?>("status_code")
                        .HasColumnType("integer");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("user_email")
                        .HasColumnType("text");

                    b.Property<string>("user_id")
                        .HasColumnType("text");

                    b.HasKey("occurred_at", "id")
                        .HasName("audit_events_202604_pkey");

                    b.HasIndex(new[] { "occurred_at" }, "audit_events_202604_occurred_at_idx");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "occurred_at" }, "audit_events_202604_occurred_at_idx"), "brin");

                    b.HasIndex(new[] { "user_id", "occurred_at" }, "audit_events_202604_user_id_occurred_at_idx")
                        .IsDescending(false, true);

                    b.ToTable("audit_events_202604", (string)null);
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.audit_events_202605", b =>
                {
                    b.Property<DateTime>("occurred_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValueSql("(gen_random_uuid())::text");

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("criticality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("duration_ms")
                        .HasColumnType("integer");

                    b.Property<string>("endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("permission_alias")
                        .HasColumnType("text");

                    b.Property<string>("permission_id")
                        .HasColumnType("text");

                    b.Property<int?>("status_code")
                        .HasColumnType("integer");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("user_email")
                        .HasColumnType("text");

                    b.Property<string>("user_id")
                        .HasColumnType("text");

                    b.HasKey("occurred_at", "id")
                        .HasName("audit_events_202605_pkey");

                    b.HasIndex(new[] { "occurred_at" }, "audit_events_202605_occurred_at_idx");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "occurred_at" }, "audit_events_202605_occurred_at_idx"), "brin");

                    b.HasIndex(new[] { "user_id", "occurred_at" }, "audit_events_202605_user_id_occurred_at_idx")
                        .IsDescending(false, true);

                    b.ToTable("audit_events_202605", (string)null);
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.audit_events_202606", b =>
                {
                    b.Property<DateTime>("occurred_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValueSql("(gen_random_uuid())::text");

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("criticality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("duration_ms")
                        .HasColumnType("integer");

                    b.Property<string>("endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("permission_alias")
                        .HasColumnType("text");

                    b.Property<string>("permission_id")
                        .HasColumnType("text");

                    b.Property<int?>("status_code")
                        .HasColumnType("integer");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("user_email")
                        .HasColumnType("text");

                    b.Property<string>("user_id")
                        .HasColumnType("text");

                    b.HasKey("occurred_at", "id")
                        .HasName("audit_events_202606_pkey");

                    b.HasIndex(new[] { "occurred_at" }, "audit_events_202606_occurred_at_idx");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "occurred_at" }, "audit_events_202606_occurred_at_idx"), "brin");

                    b.HasIndex(new[] { "user_id", "occurred_at" }, "audit_events_202606_user_id_occurred_at_idx")
                        .IsDescending(false, true);

                    b.ToTable("audit_events_202606", (string)null);
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.audit_events_default", b =>
                {
                    b.Property<DateTime>("occurred_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValueSql("(gen_random_uuid())::text");

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("criticality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("duration_ms")
                        .HasColumnType("integer");

                    b.Property<string>("endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("permission_alias")
                        .HasColumnType("text");

                    b.Property<string>("permission_id")
                        .HasColumnType("text");

                    b.Property<int?>("status_code")
                        .HasColumnType("integer");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("user_email")
                        .HasColumnType("text");

                    b.Property<string>("user_id")
                        .HasColumnType("text");

                    b.HasKey("occurred_at", "id")
                        .HasName("audit_events_default_pkey");

                    b.HasIndex(new[] { "occurred_at" }, "audit_events_default_occurred_at_idx");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "occurred_at" }, "audit_events_default_occurred_at_idx"), "brin");

                    b.HasIndex(new[] { "user_id", "occurred_at" }, "audit_events_default_user_id_occurred_at_idx")
                        .IsDescending(false, true);

                    b.ToTable("audit_events_default", (string)null);
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.branch", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("complement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp(3) without time zone");

                    b.Property<DateTime?>("established_at")
                        .HasColumnType("timestamp(3) without time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("neighborhood")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp(3) without time zone");

                    b.Property<string>("zip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id")
                        .HasName("branches_pkey");

                    b.ToTable("branches");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.brand", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp(3) without time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp(3) without time zone");

                    b.HasKey("id")
                        .HasName("brands_pkey");

                    b.HasIndex(new[] { "alias" }, "brands_alias_key")
                        .IsUnique();

                    b.HasIndex(new[] { "name" }, "brands_name_key")
                        .IsUnique();

                    b.ToTable("brands");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.category", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp(3) without time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp(3) without time zone");

                    b.HasKey("id")
                        .HasName("categories_pkey");

                    b.HasIndex(new[] { "alias" }, "categories_alias_key")
                        .IsUnique();

                    b.HasIndex(new[] { "name" }, "categories_name_key")
                        .IsUnique();

                    b.ToTable("categories");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.inventory_item", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("stock_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("stock_item_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp(3) without time zone");

                    b.HasKey("id")
                        .HasName("inventory_items_pkey");

                    b.HasIndex("stock_item_id");

                    b.HasIndex(new[] { "stock_id", "stock_item_id" }, "inventory_items_stock_id_stock_item_id_key")
                        .IsUnique();

                    b.ToTable("inventory_items");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.location", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp(3) without time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp(3) without time zone");

                    b.HasKey("id")
                        .HasName("locations_pkey");

                    b.ToTable("locations");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.movement", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("inventory_item_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.Property<string>("reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp(3) without time zone");

                    b.HasKey("id")
                        .HasName("movements_pkey");

                    b.HasIndex("inventory_item_id");

                    b.ToTable("movements");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.oauth_account", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("avatar_url")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("email_verified")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("provider_user_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp(3) without time zone");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id")
                        .HasName("oauth_accounts_pkey");

                    b.HasIndex(new[] { "user_id" }, "oauth_accounts_user_id_idx");

                    b.ToTable("oauth_accounts");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.password", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp(3) without time zone");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp(3) without time zone");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id")
                        .HasName("passwords_pkey");

                    b.HasIndex("userId");

                    b.ToTable("passwords");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.permission", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp(3) without time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp(3) without time zone");

                    b.HasKey("id")
                        .HasName("permissions_pkey");

                    b.HasIndex(new[] { "alias" }, "permissions_alias_key")
                        .IsUnique();

                    b.ToTable("permissions");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.product", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("brand_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp(3) without time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<NpgsqlTsVector>("description_tsvector")
                        .HasColumnType("tsvector");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<NpgsqlTsVector>("name_tsvector")
                        .HasColumnType("tsvector");

                    b.Property<double>("price")
                        .HasColumnType("double precision");

                    b.Property<string>("sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("subcategory_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp(3) without time zone");

                    b.HasKey("id")
                        .HasName("products_pkey");

                    b.HasIndex("brand_id");

                    b.HasIndex("subcategory_id");

                    b.HasIndex(new[] { "alias" }, "products_alias_key")
                        .IsUnique();

                    b.HasIndex(new[] { "description_tsvector" }, "products_description_tsvector_idx");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "description_tsvector" }, "products_description_tsvector_idx"), "gin");

                    b.HasIndex(new[] { "name" }, "products_name_key")
                        .IsUnique();

                    b.HasIndex(new[] { "name_tsvector" }, "products_name_tsvector_idx");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "name_tsvector" }, "products_name_tsvector_idx"), "gin");

                    b.HasIndex(new[] { "sku" }, "products_sku_key")
                        .IsUnique();

                    b.ToTable("products");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.product_characteristic", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp(3) without time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("productId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp(3) without time zone");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id")
                        .HasName("product_characteristics_pkey");

                    b.HasIndex("productId");

                    b.ToTable("product_characteristics");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.product_image", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp(3) without time zone");

                    b.Property<string>("productId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp(3) without time zone");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id")
                        .HasName("product_images_pkey");

                    b.HasIndex("productId");

                    b.ToTable("product_images");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.role", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp(3) without time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp(3) without time zone");

                    b.HasKey("id")
                        .HasName("roles_pkey");

                    b.HasIndex(new[] { "name" }, "roles_name_key")
                        .IsUnique();

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.role_permission", b =>
                {
                    b.Property<string>("role_id")
                        .HasColumnType("text");

                    b.Property<string>("permission_id")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("role_id", "permission_id")
                        .HasName("role_permissions_pkey");

                    b.HasIndex(new[] { "permission_id" }, "role_permissions_permission_id_idx");

                    b.ToTable("role_permissions");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.snapshot", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("inventory_item_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("processed_at")
                        .HasColumnType("timestamp(3) without time zone");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp(3) without time zone");

                    b.HasKey("id")
                        .HasName("snapshots_pkey");

                    b.HasIndex("inventory_item_id");

                    b.ToTable("snapshots");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.stock", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp(3) without time zone");

                    b.Property<string>("location_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp(3) without time zone");

                    b.HasKey("id")
                        .HasName("stocks_pkey");

                    b.HasIndex(new[] { "location_id" }, "stocks_location_id_key")
                        .IsUnique();

                    b.ToTable("stocks");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.stock_item", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<int>("costPrice")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp(3) without time zone");

                    b.Property<int>("salePrice")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp(3) without time zone");

                    b.HasKey("id")
                        .HasName("stock_items_pkey");

                    b.ToTable("stock_items");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.subcategory", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp(3) without time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("order")
                        .HasColumnType("integer");

                    b.Property<string>("parentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp(3) without time zone");

                    b.HasKey("id")
                        .HasName("subcategories_pkey");

                    b.HasIndex("parentId");

                    b.HasIndex(new[] { "alias" }, "subcategories_alias_key")
                        .IsUnique();

                    b.HasIndex(new[] { "name", "parentId" }, "subcategories_name_parentId_key")
                        .IsUnique();

                    b.ToTable("subcategories");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.user", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("avatar_url")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp(3) without time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp(3) without time zone");

                    b.HasKey("id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.user_role", b =>
                {
                    b.Property<string>("user_id")
                        .HasColumnType("text");

                    b.Property<string>("role_id")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("user_id", "role_id")
                        .HasName("user_roles_pkey");

                    b.HasIndex(new[] { "role_id" }, "user_roles_role_id_idx");

                    b.ToTable("user_roles");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.inventory_item", b =>
                {
                    b.HasOne("Homelab.Data.Data.Entities.stock", "stock")
                        .WithMany("inventory_items")
                        .HasForeignKey("stock_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("inventory_items_stock_id_fkey");

                    b.HasOne("Homelab.Data.Data.Entities.stock_item", "stock_item")
                        .WithMany("inventory_items")
                        .HasForeignKey("stock_item_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("inventory_items_stock_item_id_fkey");

                    b.Navigation("stock");

                    b.Navigation("stock_item");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.movement", b =>
                {
                    b.HasOne("Homelab.Data.Data.Entities.inventory_item", "inventory_item")
                        .WithMany("movements")
                        .HasForeignKey("inventory_item_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("movements_inventory_item_id_fkey");

                    b.Navigation("inventory_item");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.oauth_account", b =>
                {
                    b.HasOne("Homelab.Data.Data.Entities.user", "user")
                        .WithMany("oauth_accounts")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("oauth_accounts_user_id_fkey");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.password", b =>
                {
                    b.HasOne("Homelab.Data.Data.Entities.user", "user")
                        .WithMany("passwords")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("passwords_userId_fkey");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.product", b =>
                {
                    b.HasOne("Homelab.Data.Data.Entities.brand", "brand")
                        .WithMany("products")
                        .HasForeignKey("brand_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("products_brand_id_fkey");

                    b.HasOne("Homelab.Data.Data.Entities.subcategory", "subcategory")
                        .WithMany("products")
                        .HasForeignKey("subcategory_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("products_subcategory_id_fkey");

                    b.Navigation("brand");

                    b.Navigation("subcategory");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.product_characteristic", b =>
                {
                    b.HasOne("Homelab.Data.Data.Entities.product", "product")
                        .WithMany("product_characteristics")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("product_characteristics_productId_fkey");

                    b.Navigation("product");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.product_image", b =>
                {
                    b.HasOne("Homelab.Data.Data.Entities.product", "product")
                        .WithMany("product_images")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("product_images_productId_fkey");

                    b.Navigation("product");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.role_permission", b =>
                {
                    b.HasOne("Homelab.Data.Data.Entities.permission", "permission")
                        .WithMany("role_permissions")
                        .HasForeignKey("permission_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("role_permissions_permission_id_fkey");

                    b.HasOne("Homelab.Data.Data.Entities.role", "role")
                        .WithMany("role_permissions")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("role_permissions_role_id_fkey");

                    b.Navigation("permission");

                    b.Navigation("role");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.snapshot", b =>
                {
                    b.HasOne("Homelab.Data.Data.Entities.inventory_item", "inventory_item")
                        .WithMany("snapshots")
                        .HasForeignKey("inventory_item_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("snapshots_inventory_item_id_fkey");

                    b.Navigation("inventory_item");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.stock", b =>
                {
                    b.HasOne("Homelab.Data.Data.Entities.location", "location")
                        .WithOne("stock")
                        .HasForeignKey("Homelab.Data.Data.Entities.stock", "location_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("stocks_location_id_fkey");

                    b.Navigation("location");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.subcategory", b =>
                {
                    b.HasOne("Homelab.Data.Data.Entities.category", "parent")
                        .WithMany("subcategories")
                        .HasForeignKey("parentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("subcategories_parentId_fkey");

                    b.Navigation("parent");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.user_role", b =>
                {
                    b.HasOne("Homelab.Data.Data.Entities.role", "role")
                        .WithMany("user_roles")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_roles_role_id_fkey");

                    b.HasOne("Homelab.Data.Data.Entities.user", "user")
                        .WithMany("user_roles")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_roles_user_id_fkey");

                    b.Navigation("role");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.brand", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.category", b =>
                {
                    b.Navigation("subcategories");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.inventory_item", b =>
                {
                    b.Navigation("movements");

                    b.Navigation("snapshots");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.location", b =>
                {
                    b.Navigation("stock");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.permission", b =>
                {
                    b.Navigation("role_permissions");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.product", b =>
                {
                    b.Navigation("product_characteristics");

                    b.Navigation("product_images");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.role", b =>
                {
                    b.Navigation("role_permissions");

                    b.Navigation("user_roles");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.stock", b =>
                {
                    b.Navigation("inventory_items");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.stock_item", b =>
                {
                    b.Navigation("inventory_items");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.subcategory", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Homelab.Data.Data.Entities.user", b =>
                {
                    b.Navigation("oauth_accounts");

                    b.Navigation("passwords");

                    b.Navigation("user_roles");
                });
#pragma warning restore 612, 618
        }
    }
}
